# Dependencies
markdown:         redcarpet
highlighter:         true

# Permalinks
permalink:        pretty

gems: [jekyll-paginate]

# Setup
title:            Servers For Managers
tagline:          'Understand technical words and terms in the perspective of manager.'
description:      'A web development blog which aims to help project managers, product owners abd businessmen to understand very technical terms and how it relates to their businesses.'
url:              https://www.serversformanagers.com

author:
  name:           'Darwin Biler'
  url:            https://www.darwinbiler.com

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/serversformanagers/serversformanagers.github.io
